cmake_minimum_required(VERSION 3.29)
project(keyhunt-pvk CXX CUDA)

####################################################################################################################################################################################
# Set the C++ standard
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)

################################################################################################################################################################################
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
#set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded")

################################################################################################################################################################################
include(cmake/utils.cmake)
include_needed_libs()
fetch_and_include_needed_libs()
configure_global_compilation_flags()

####################################################################################################################################################################################
option(BUILD_TESTS "Build test_bitcoin executable." OFF)

####################################################################################################################################################################################
include_directories(${CMAKE_SOURCE_DIR})

####################################################################################################################################################################################
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/bin)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE ${CMAKE_SOURCE_DIR}/bin)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG ${CMAKE_SOURCE_DIR}/bin)

####################################################################################################################################################################################
add_subdirectory(util)
add_subdirectory(cuda)
add_subdirectory(tools)
add_subdirectory(key_hunter)

# TESTS ############################################################################################################################################################################
if(BUILD_TESTS)
    enable_testing()
    add_subdirectory(tests)
endif()

####################################################################################################################################################################################
