####################################################################################################################################################################################
set(SRC
    main.cpp
)
add_executable(cuda-mnemonic-hunter ${SRC})

target_link_libraries(cuda-mnemonic-hunter PRIVATE util)
target_link_libraries(cuda-mnemonic-hunter PRIVATE wallycore libsecp256k1)
####################################################################################################################################################################################
