####################################################################################################################################################################################
suppress_msvc_warnings()

####################################################################################################################################################################################
link_libraries(util)
link_libraries(Boost::log Boost::log_setup Boost::iostreams)

####################################################################################################################################################################################
add_executable(gpu_info gpu_info.cpp)
target_link_libraries(gpu_info PRIVATE CUDA::cudart_static)

####################################################################################################################################################################################
add_executable(decrypt_results decrypt_results.cpp)

####################################################################################################################################################################################
add_executable(convert_hash160_to_binary convert_hash160_to_binary.cpp)

####################################################################################################################################################################################